Trying:
    encode('SOS')
Expecting:
    '... --- ...'
ok
Trying:
    encode('PY'*8) # doctest: +ELLIPSIS
Expecting:
    '.--. -.-- ... .--. -.--'
ok
Trying:
    encode(123)
Expecting:
    Traceback (most recent call last):
    TypeError: 'int' object is not iterable
ok
Trying:
    encode('!')
Expecting:
    Traceback (most recent call last):
    KeyError: '*'
**********************************************************************
File "C:\Users\Mila\Desktop\hw5\issue_01\morse_encode.py", line 45, in morse_encode.encode
Failed example:
    encode('!')
Expected:
    Traceback (most recent call last):
    KeyError: '*'
Got:
    Traceback (most recent call last):
      File "D:\anaconda3\lib\doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest morse_encode.encode[3]>", line 1, in <module>
        encode('!')
    KeyError: '!'
1 items had no tests:
    morse_encode
**********************************************************************
1 items had failures:
   1 of   4 in morse_encode.encode
4 tests in 2 items.
3 passed and 1 failed.
***Test Failed*** 1 failures.